### ISSUE TITLE
Error: Cannot find module 'prettier/parser-babylon'

### ISSUE THREAD

**Issue by elyesbenabdelkader** [ifiokjr/prettier-plugin-sorted#1]
```
Error: Cannot find module 'prettier/parser-babylon'
Require stack:
- ./node_modules/prettier-plugin-sorted/dist/prettier-plugin-sorted.cjs.development.js
- ./node_modules/prettier-plugin-sorted/dist/index.js
- ./node_modules/prettier/bin-prettier.js
```

I'm pretty sure this is caused by the [deprecated parser](https://prettier.io/blog/2019/01/20/1.16.0.html#rename-babylon-parser-to-babel-5647-by-wuweiweiwu) in prettier 1.16.0. It was [removed](https://prettier.io/blog/2020/03/21/2.0.0.html#remove-deprecated-options-and-option-values-6993httpsgithubcomprettierprettierpull6993-7511httpsgithubcomprettierprettierpull7511-7533httpsgithubcomprettierprettierpull7533-7535httpsgithubcomprettierprettierpull7535-7536httpsgithubcomprettierprettierpull7536-by-fiskerhttpsgithubcomfisker) in prettier 2.0

**Comment by leosuncin** [comment]
Same issue
